apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: broadcaster-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/l7mp/multicluster-broadcaster-swm-l7mp
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: broadcaster
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: broadcaster-repo
  path: ./manifests/flux/germany  # Should point to the given cluster
  prune: false  # Do not allow Flux to remove resources not in the repo
  wait: true