apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/statefulset.yaml
- ../base/ingress.yaml

#nameSuffix: -us-west

# Patch to modify environment variables
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: "broadcaster-us-west"
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "turn:us-west.broadcaster.stunner.cc:3478?transport=udp"
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "us-west.broadcaster.stunner.cc"
  target:
    kind: StatefulSet
    name: broadcaster
    namespace: default
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: us-west.broadcaster.stunner.cc
    - op: replace
      path: /spec/rules/0/host
      value: us-west.broadcaster.stunner.cc
  target:
    kind: Ingress
    name: broadcaster-ingress
    namespace: default